{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_feature_story.TestLogin object at 0x7fa3d8a85ba8>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:91: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1685431170105, "stop": 1685431170105}, {"name": "点击密码", "status": "passed", "start": 1685431170105, "stop": 1685431170105}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"/Users/liaoboyang/pythonProject10测试报告/test_feature_story.py\", line 91, in test_login_failure\n    assert '1' == 1\n"}, "start": 1685431170105, "stop": 1685431170105}], "attachments": [{"name": "stdout", "source": "2a8bfe62-5cd9-48de-b1a5-90c3a709157e-attachment.txt", "type": "text/plain"}], "start": 1685431170105, "stop": 1685431170105, "uuid": "cb67154a-94cd-4237-9233-85150dbc4eac", "historyId": "a34b019e1682c8c99a5a404099cd759a", "testCaseId": "a34b019e1682c8c99a5a404099cd759a", "fullName": "test_feature_story#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "liaoboyangdeMacBook-Air.local"}, {"name": "thread", "value": "12986-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}